name: "context"

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
        run: |
          echo "${MY_ACTION}"
          echo "${MY_ACTOR}"
