name: "context"

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MY_ACTION: ${{ github.action }}
      MY_ACTOR: ${{ github.actor }}
    steps:
      - run: |
          echo "${MY_ACTION}"
          echo "${MY_ACTOR}"
